### PR TITLE
Initial encrypted protocol support

### PR DESCRIPTION
**Pull request by MPM1107**

### CODE REVIEW

**Comment by cyrilvincler** [comment]
@MPM1107 does it work properly with freestyle 2 device, tested with real device? I have a few questions about your approach can you contact me in private? (cyril@vincler.fr)

**Comment by Flameeyes** [comment]
So I'm now starting to take a look to this. My general idea is to start trying to implement this using a separate Speck implementation (https://pypi.org/project/simonspeckciphers/) so that it's very very clear that the encryption is not copied from anywhere in particular, and has no copyright issue.

**Comment by MPM1107** [comment]
Sounds good, that implementation looks very similar to mine, should work. It's just missing the CMAC part, which is also standard, but I don't see any suitable 3rd party libs for that after a quick google search, they're all a part of bigger crypto libs that don't implement speck. Not sure what the best way to solve that would be.

**Comment by Flameeyes** [comment]
Yeah I played around with it a bit but you're right it's not quite satisfying as it is :/

If pycryptodome supported Speck, then we would be good to go, maybe I should file a feature request.

**Comment by Flameeyes** [comment]
Merged your commit with style/testing/interface changes, freestyle-keys is released, and I'm now going to tag this version as freestyle-hid-1.1.0.

I'm making glucometerutils changes now!

**Pull request closed without merging**
